import { test, expect, type Page } from '@playwright/test';

/**
 * Valid 1x1 pixel red PNG as a Node.js Buffer for API uploads.
 * Generated by sharp to guarantee libspng compatibility.
 */
const TEST_PNG_BASE64 =
	'iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAIAAACQd1PeAAAACXBIWXMAAAPoAAAD6AG1e1JrAAAADElEQVR4nGP4z8AAAAMBAQDJ/pLvAAAAAElFTkSuQmCC';

function createTestPngBuffer(): Buffer {
	return Buffer.from(TEST_PNG_BASE64, 'base64');
}

/**
 * Generate a unique slug for each test.
 */
function uniqueSlug(prefix: string): string {
	return `${prefix}-${Date.now()}-${Math.random().toString(36).slice(2, 8)}`;
}

/**
 * Upload a test PNG via the API and return the image metadata.
 */
async function uploadImageViaApi(
	page: Page,
	slug: string
): Promise<{ id: string; filename: string; size: number; sort_order: number }> {
	const pngBuffer = createTestPngBuffer();
	const response = await page.request.post(`/api/pads/${slug}/images`, {
		multipart: {
			image: {
				name: 'test.png',
				mimeType: 'image/png',
				buffer: pngBuffer
			}
		}
	});
	expect(response.status()).toBe(201);
	return response.json();
}

test.describe('Image Management', () => {
	test('IMG-01: clicking thumbnail opens lightbox with full-size image', async ({ page }) => {
		const slug = uniqueSlug('test-img-lightbox');

		// Upload an image via API first
		const result = await uploadImageViaApi(page, slug);

		// Navigate to the pad
		await page.goto(`/${slug}`);
		await page.waitForLoadState('networkidle');

		// Wait for the image to appear in the grid
		const img = page.locator('.image-card .image-button img').first();
		await expect(img).toBeVisible({ timeout: 10000 });

		// Click the thumbnail to open lightbox
		await page.locator('.image-card .image-button').first().click();

		// Lightbox overlay should be visible
		const overlay = page.locator('.lightbox-overlay');
		await expect(overlay).toBeVisible({ timeout: 5000 });

		// Lightbox image should have the correct src containing the image UUID
		const lightboxImg = page.locator('.lightbox-image');
		await expect(lightboxImg).toBeVisible();
		const src = await lightboxImg.getAttribute('src');
		expect(src).toContain(result.id);
	});

	test('IMG-01: pressing Escape closes the lightbox', async ({ page }) => {
		const slug = uniqueSlug('test-img-lightbox-esc');

		// Upload an image via API
		await uploadImageViaApi(page, slug);

		// Navigate to the pad
		await page.goto(`/${slug}`);
		await page.waitForLoadState('networkidle');

		// Wait for image to appear
		const img = page.locator('.image-card .image-button').first();
		await expect(img).toBeVisible({ timeout: 10000 });

		// Open lightbox
		await img.click();
		await expect(page.locator('.lightbox-overlay')).toBeVisible({ timeout: 5000 });

		// Press Escape
		await page.keyboard.press('Escape');

		// Lightbox should close
		await expect(page.locator('.lightbox-overlay')).not.toBeVisible({ timeout: 3000 });
	});

	test('IMG-01: delete button removes image from grid', async ({ page }) => {
		const slug = uniqueSlug('test-img-delete');

		// Upload an image via API
		const result = await uploadImageViaApi(page, slug);

		// Navigate to the pad
		await page.goto(`/${slug}`);
		await page.waitForLoadState('networkidle');

		// Wait for the image to appear
		await expect(page.locator('.image-card .image-button img').first()).toBeVisible({
			timeout: 10000
		});

		// Hover over the image card to reveal delete button
		await page.locator('.image-card').first().hover();

		// Click the delete button
		const deleteBtn = page.locator('.delete-btn').first();
		await expect(deleteBtn).toBeVisible({ timeout: 3000 });
		await deleteBtn.click();

		// Image card should be removed from the grid
		await expect(page.locator('.image-card')).not.toBeVisible({ timeout: 5000 });

		// Verify via API that the image is gone (returns 404)
		const imageResponse = await page.request.get(`/api/pads/${slug}/images/${result.id}`);
		expect(imageResponse.status()).toBe(404);
	});

	test('IMG-01: image grid is not visible when pad has no images', async ({ page }) => {
		const slug = uniqueSlug('test-img-empty');

		// Navigate to a fresh pad with no images
		await page.goto(`/${slug}`);
		await page.waitForLoadState('networkidle');

		// The image-grid section should not be in the DOM (ImageGrid renders nothing when images.length === 0)
		await expect(page.locator('.image-grid')).not.toBeVisible({ timeout: 3000 });
		await expect(page.locator('.image-section')).not.toBeVisible({ timeout: 1000 });
	});

	test('IMG-02: deleted image file no longer served', async ({ page }) => {
		const slug = uniqueSlug('test-img-delete-api');

		// Upload an image via API
		const result = await uploadImageViaApi(page, slug);

		// Verify image is initially accessible
		const beforeResponse = await page.request.get(`/api/pads/${slug}/images/${result.id}`);
		expect(beforeResponse.status()).toBe(200);

		// Delete via API
		const deleteResponse = await page.request.delete(`/api/pads/${slug}/images/${result.id}`);
		expect(deleteResponse.status()).toBe(200);
		const deleteBody = await deleteResponse.json();
		expect(deleteBody.deleted).toBe(true);

		// Image should now return 404
		const afterResponse = await page.request.get(`/api/pads/${slug}/images/${result.id}`);
		expect(afterResponse.status()).toBe(404);
	});
});
